-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 12:07:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app` ;

-- -----------------------------------------------------
-- Schema app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8 ;
USE `app` ;

-- -----------------------------------------------------
-- Table `app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`users` ;

CREATE TABLE IF NOT EXISTS `app`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `e-mail` VARCHAR(255) NOT NULL,
  `active` TINYINT NULL,
  `avatar_url` VARCHAR(255) NULL,
  `description` VARCHAR(1000) NULL,
  `created_timestamp` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`practice_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`practice_set` ;

CREATE TABLE IF NOT EXISTS `app`.`practice_set` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `set_name` VARCHAR(255) NOT NULL,
  `created_timestamp` DATETIME(3) NULL,
  `last_edited_timestamp` DATETIME(3) NULL,
  `private` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_practice_sets_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`practice_set_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`practice_set_tags` ;

CREATE TABLE IF NOT EXISTS `app`.`practice_set_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `practice_set_id` INT NOT NULL,
  `tag` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `practice_set_id`),
  CONSTRAINT `fk_practice_set_id_tags`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_set` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`practice_set_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`practice_set_item` ;

CREATE TABLE IF NOT EXISTS `app`.`practice_set_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `practice_set_id` INT NOT NULL,
  `question` VARCHAR(1000) NOT NULL,
  `answer` VARCHAR(1000) NOT NULL,
  `order` INT NULL,
  PRIMARY KEY (`id`, `practice_set_id`),
  CONSTRAINT `fk_practice_set_id_contents`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`practice_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`practice_session` ;

CREATE TABLE IF NOT EXISTS `app`.`practice_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `practice_set_id` INT NOT NULL,
  `time_started` DATETIME(3) NULL,
  `time_ended` DATETIME(3) NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_practice_set_id_session`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id_session`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`practice_session_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`practice_session_item` ;

CREATE TABLE IF NOT EXISTS `app`.`practice_session_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `practice_session_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `user_answer` TINYINT NULL,
  `time_started` DATETIME(3) NULL,
  `time_ended` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_practice_session_id_item`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_practice_set_id_session_item`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_set_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app`.`favorite_practice_sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app`.`favorite_practice_sets` ;

CREATE TABLE IF NOT EXISTS `app`.`favorite_practice_sets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `practice_set_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_favorite_practice_sets_user_id`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_practice_sets_practice_set_id`
    FOREIGN KEY (`id`)
    REFERENCES `app`.`practice_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
